baseURL = "https://www.bebocard.com"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "BeboCard"
[markup.goldmark.renderer]
unsafe = true
[menu]
footer_right = []
main = []
[[menu.footer_left]]
URL = "#"
name = "Blog"
[[menu.footer_left]]
URL = "https://www.linkedin.com/company/roadenn"
name = "Linkedin"
[[menu.footer_left]]
URL = "https://twitter.com/"
name = "Twitter"
[[menu.footer_middle]]
URL = "https://www.bebocard.com/"
name = "Site Internet"
[[menu.footer_middle]]
URL = "https://www.linkedin.com"
name = "Linkedin"
[[menu.footer_middle]]
URL = "https://twitter.com/"
name = "Twitter"
[params]
author = "MuthuPrabu"
contact_form_action = "NewSub"
copyright = "Powered By [BeboCard](https://www.linkedin.com/) Design By [Bebocard](https://www.bebocard.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
description = "BeboCard provides with products enable customers"
footer_content = "The best the users can get"
footer_menu_left = "BeboCard"
footer_menu_middle = "NewSub"
footer_menu_right = ""
logo = "/images/bebo.png"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Contact Us"
link = "https://form.typeform.com/to/ASAPxXgW"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/"
title = "Linkedin"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/"
title = "Twitter"
