baseURL = "http://roadenn.netlify.com"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Roadenn"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Us"
weight = 3
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
weight = 2
[[menu.footer_left]]
URL = "pricing"
name = "Pricing"
weight = 1
[[menu.footer_middle]]
URL = "#"
name = "Features"
weight = 1
[[menu.footer_middle]]
URL = "#"
name = "Platform"
weight = 2
[[menu.footer_middle]]
URL = "pricing"
name = "Pricing"
weight = 3
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 2
[[menu.footer_right]]
URL = "faq"
name = "FAQ"
weight = 1
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 3
[params]
author = "Tanguy LE BARBER"
contact_form_action = "#"
copyright = "Power By [Tanguy LE BARBER](https://www.linkedin.com/in/tanguylebarber/) Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
description = "Roadenn a consulting company for your digital transformation"
footer_content = "Digital transformation & Change management Consulting Company - We are French Tech Vietnam member"
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
logo = "/images/roadenn2.png"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Contact Us"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/roadenn/"
title = "linkedin"
